# -*- coding: utf-8 -*-
"""ML_2ndWeek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8tBAKDpansT00Fbo4Ua73uDPwTWcPnJ
"""

from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = np.array([[i] for i in range(2, 10000)])
y = []

for n in range(2, 10000):
    is_prime = True

    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            is_prime = False
            break

    y.append(1 if is_prime else 0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print(f"\nModel Accuracy on unseen data: {accuracy * 100:.2f}%")

print("Enter 3 numbers:")
for i in range(3):
    n = int(input(f"Enter number {i + 1}: "))
    prediction = model.predict([[n]])[0]
    if prediction == 1:
        print(n, "is Prime")
    else:
        print(n, "is Not Prime")