# -*- coding: utf-8 -*-
"""ML_1stWeek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4x2uyD8_WnlsLLXY8yPGbPXyOq5Mibj
"""

from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([
    [1, 2],
    [2, 3],
    [4, 5],
    [10, 20],
    [7, 8],
    [5,9],
    [11,7],
    [15,16],
    [9,17],
    [14,18],

])

y = np.array([3, 5, 9, 30, 15, 14, 18, 31, 26, 32])

model = LinearRegression()
model.fit(X, y)

test = np.array([[15, 25], [6, 14], [4, 3]])

print("15 + 25 =", model.predict([test[0]])[0])
print("6 + 14 =", model.predict([test[1]])[0])
print("4 + 3 =", model.predict([test[2]])[0])
